### ISSUE TITLE
RealVolume.onRingerModeChanged.listen not called

### ISSUE THREAD

**Issue by heshesh2010** [Pana-g/real_volume#11]
Hi , 

I call RealVolume.onRingerModeChanged.listen  but it called once but not called again when ringer changed but when i call    RealVolume.onVolumeChanged.listen it works every time 

what i want is like inistagram app so user set ringer silent so videos goes to silent , when user hit volume up then videos play sound . 

my code  in video player widget item 

`   

       if (mounted) {
      controller = BetterPlayerListVideoPlayerController();
      WidgetsBinding.instance.addPostFrameCallback((_) async {
        print(await RealVolume.getCurrentVol(StreamType.SYSTEM));
        if ((await RealVolume.getCurrentVol(StreamType.SYSTEM) == 0.0 ||
                await RealVolume.getRingerMode() == RingerMode.SILENT ||
                await RealVolume.getRingerMode() == RingerMode.VIBRATE) &&
            account.isVideoSoundOff == true) {
          controller?.setVolume(0);
          print("videoMuted and sharedPrefrences is" +
              account.isVideoSoundOff.toString());
        } else {
          print("video not Muted and sharedPrefrences is:" +
              account.isVideoSoundOff.toString());
          controller?.setVolume(1);
        }
      });
      RealVolume.onVolumeChanged.listen((event) async {
        if (event.volumeLevel == 0.0) {
          account.isVideoSoundOff = true;
          print("volum down ");
          controller?.setVolume(0);
        } else {
          account.isVideoSoundOff = false;
          print("volum up ");
          controller?.setVolume(1);
        }
      });

      var volStream =
          RealVolume.onRingerModeChanged.listen((RingerMode event) async {
        if (event == RingerMode.SILENT || event == RingerMode.VIBRATE) {
          account.isVideoSoundOff = true;
          print("video  Muted");
          controller?.setVolume(0);
        } else {
          print("video not Muted");
          account.isVideoSoundOff = false;
          controller?.setVolume(1);
        }
      });
      volStream.cancel();
      betterPlayerConfiguration = BetterPlayerConfiguration(
        looping: true,
        //   autoPlay: true,
      ); //  _setupController();
      }
`

**Comment by Pana-g** [comment]
@heshesh2010  Are you seeing this behavior on an iOS device? Please check also this section https://pub.dev/packages/real_volume#ios

**Comment by heshesh2010** [comment]
@Pana-g Yes i tested with ios real device

**Comment by Pana-g** [comment]
@heshesh2010 
> NOTE_2: For iOS devices if you call getRingerMode AFTER you have subscribed to onRingerModeChanged listener the listener will stop working. So keep in mind that if you want to use both of them in the same project you need to cancel and re-subscribe to onRingerModeChanged listener AFTER you have called getRingerMode function.

I think this is the issue you see

**Comment by heshesh2010** [comment]
> @heshesh2010
> 
> > NOTE_2: For iOS devices if you call getRingerMode AFTER you have subscribed to onRingerModeChanged listener the listener will stop working. So keep in mind that if you want to use both of them in the same project you need to cancel and re-subscribe to onRingerModeChanged listener AFTER you have called getRingerMode function.
> 
> I think this is the issue you see

yes , and i called cancel as u see in my first post , but still didn't work , can u help me with the right code i should use in this case or u have ' cancel ' example

**Comment by Pana-g** [comment]
Try the following code:
```
if (mounted) {
      controller = BetterPlayerListVideoPlayerController();
      WidgetsBinding.instance.addPostFrameCallback((_) async {
        print(await RealVolume.getCurrentVol(StreamType.SYSTEM));
        if ((await RealVolume.getCurrentVol(StreamType.SYSTEM) == 0.0 ||
                await RealVolume.getRingerMode() == RingerMode.SILENT ||
                await RealVolume.getRingerMode() == RingerMode.VIBRATE) &&
            account.isVideoSoundOff == true) {
          controller?.setVolume(0);
          print("videoMuted and sharedPrefrences is${account.isVideoSoundOff}");
        } else {
          print(
              "video not Muted and sharedPrefrences is:${account.isVideoSoundOff}");
          controller?.setVolume(1);
        }
        RealVolume.onVolumeChanged.listen((event) async {
          if (event.volumeLevel == 0.0) {
            account.isVideoSoundOff = true;
            print("volum down ");
            controller?.setVolume(0);
          } else {
            account.isVideoSoundOff = false;
            print("volum up ");
            controller?.setVolume(1);
          }
        });

        var volStream =
            RealVolume.onRingerModeChanged.listen((RingerMode event) async {
          if (event == RingerMode.SILENT || event == RingerMode.VIBRATE) {
            account.isVideoSoundOff = true;
            print("video  Muted");
            controller?.setVolume(0);
          } else {
            print("video not Muted");
            account.isVideoSoundOff = false;
            controller?.setVolume(1);
          }
        });
        betterPlayerConfiguration = BetterPlayerConfiguration(
          looping: true,
          //   autoPlay: true,
        ); //  _setupController();
      });
    } 
```

**Comment by heshesh2010** [comment]
> @heshesh2010 I see that you are using the `onRingerModeChanged` listener and the `RealVolume.getRingerMode()` in an asynchronus way. Please try the following code:
> 
> ```
> if (mounted) {
>       controller = BetterPlayerListVideoPlayerController();
>       WidgetsBinding.instance.addPostFrameCallback((_) async {
>         print(await RealVolume.getCurrentVol(StreamType.SYSTEM));
>         if ((await RealVolume.getCurrentVol(StreamType.SYSTEM) == 0.0 ||
>                 await RealVolume.getRingerMode() == RingerMode.SILENT ||
>                 await RealVolume.getRingerMode() == RingerMode.VIBRATE) &&
>             account.isVideoSoundOff == true) {
>           controller?.setVolume(0);
>           print("videoMuted and sharedPrefrences is${account.isVideoSoundOff}");
>         } else {
>           print(
>               "video not Muted and sharedPrefrences is:${account.isVideoSoundOff}");
>           controller?.setVolume(1);
>         }
>         RealVolume.onVolumeChanged.listen((event) async {
>           if (event.volumeLevel == 0.0) {
>             account.isVideoSoundOff = true;
>             print("volum down ");
>             controller?.setVolume(0);
>           } else {
>             account.isVideoSoundOff = false;
>             print("volum up ");
>             controller?.setVolume(1);
>           }
>         });
> 
>         var volStream =
>             RealVolume.onRingerModeChanged.listen((RingerMode event) async {
>           if (event == RingerMode.SILENT || event == RingerMode.VIBRATE) {
>             account.isVideoSoundOff = true;
>             print("video  Muted");
>             controller?.setVolume(0);
>           } else {
>             print("video not Muted");
>             account.isVideoSoundOff = false;
>             controller?.setVolume(1);
>           }
>         });
>         betterPlayerConfiguration = BetterPlayerConfiguration(
>           looping: true,
>           //   autoPlay: true,
>         ); //  _setupController();
>       });
>     } 
> ```

it works thank you

**Comment by heshesh2010** [comment]
I see RealVolume.onRingerModeChanged.listen called each time i play the video even I don't change the ringer mode , it must be called only if i changed the ringer mode off or on , but it called every time now .

**Comment by Pana-g** [comment]
@heshesh2010 This makes sense since you call everything within `WidgetsBinding.instance.addPostFrameCallback`. If you don't want to call this every time the widget is build just remove `WidgetsBinding.instance.addPostFrameCallback` for example: 
``` dart
if (mounted) {
      controller = BetterPlayerListVideoPlayerController();
      print(await RealVolume.getCurrentVol(StreamType.SYSTEM));
      if ((await RealVolume.getCurrentVol(StreamType.SYSTEM) == 0.0 ||
              await RealVolume.getRingerMode() == RingerMode.SILENT ||
              await RealVolume.getRingerMode() == RingerMode.VIBRATE) &&
          account.isVideoSoundOff == true) {
        controller?.setVolume(0);
        print("videoMuted and sharedPrefrences is${account.isVideoSoundOff}");
      } else {
        print(
            "video not Muted and sharedPrefrences is:${account.isVideoSoundOff}");
        controller?.setVolume(1);
      }
      RealVolume.onVolumeChanged.listen((event) async {
        if (event.volumeLevel == 0.0) {
          account.isVideoSoundOff = true;
          print("volum down ");
          controller?.setVolume(0);
        } else {
          account.isVideoSoundOff = false;
          print("volum up ");
          controller?.setVolume(1);
        }
      });

      var volStream =
          RealVolume.onRingerModeChanged.listen((RingerMode event) async {
        if (event == RingerMode.SILENT || event == RingerMode.VIBRATE) {
          account.isVideoSoundOff = true;
          print("video  Muted");
          controller?.setVolume(0);
        } else {
          print("video not Muted");
          account.isVideoSoundOff = false;
          controller?.setVolume(1);
        }
      });
      betterPlayerConfiguration = BetterPlayerConfiguration(
        looping: true,
        //   autoPlay: true,
      ); //  _setupController();
    }

**Comment by Pana-g** [comment]
In case you want to use this inside a `StatefulWidget` just call it once in `initState` and this should do the trick.

**Comment by heshesh2010** [comment]
yes it's already working , but the problem is the is called  RealVolume.onRingerModeChanged every time the widget is init , it must be called when i press ringer mode button only

**Comment by Pana-g** [comment]
Since `RealVolume.onRingerModeChanged.listen` is a global listener you can use it once on your parent widget and access its value through a global state management tool like [flutter_bloc](https://pub.dev/packages/flutter_bloc) or [getX](https://pub.dev/packages/get) on any children. It makes sense to see this kind of behavior if you are building and disposing the same compoenet. Also keep in mind that you need to dispose these listeners as well on widget dispose. I could help you even more if you could provide a more thorough example of what you are trying to achieve.
