### ISSUE TITLE
Gradle sync failed

### ISSUE THREAD

**Issue by appledev-67** [Pana-g/real_volume#4]
build.gradle:real_volume

Gradle sync failed: Could not find method provided() for arguments [file collection] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

**Comment by Pana-g** [comment]
@appledev-67 Can you provide more info about this? For example which gradle version you are using and which flutter version you are using?

**Comment by Pana-g** [comment]
@appledev-67 I've just updated the plugin with a fix for this. Please let me know if the issue has been resolved.
