### ISSUE TITLE
Audio Listener not working when Bluetooth is connected

### ISSUE THREAD

**Issue by vmwsree** [Pana-g/real_volume#5]
I'm having an issue with the Audio Listener in the real_volume repository. When I am not connected to Bluetooth, the Audio Listener is working as expected and I am getting a response. However, when I connect Bluetooth, both the hardware button and the Bluetooth audio button stop working and I am not getting a response.

I'm not sure what is causing this issue or how to fix it. Any help or suggestions would be greatly appreciated. Thanks in advance for your time and assistance.

Edit: Its working on iOS but not on Android

**Comment by Pana-g** [comment]
@vmwsree Can you please paste the output of `flutter doctor -v` .

**Comment by Pana-g** [comment]
@vmwsree I tried to emulate this behavior in a Redmi Note 11 Pro and I wasn't able. What mobile device are you using for testing?

**Comment by Pana-g** [comment]
Closing as inactive
