### ISSUE TITLE
Need Solution

### ISSUE THREAD

**Issue by moinkhan780** [Pana-g/real_volume#6]
Is there any way to control 4 volumes (Media, System, Ring, Notification) with single slider 

Currently i'm using setVolume for all 4 stream and passing same value in each stream but its giving me wrong inifinite loop behavious

**Comment by Pana-g** [comment]
Hi @moinkhan780 can you providfe a code example?

**Comment by moinkhan780** [comment]
> Hi @moinkhan780 can you provide a code example?

Closing for now.
Thank you for the response.
