### ISSUE TITLE
[Android] Bug: Alarm volume listener now always work

### ISSUE THREAD

**Issue by dtkdt100** [Pana-g/real_volume#7]
I am using Google Pixel 6 and the alarm volume has 7 steps.

When the volume is from 1 to 3 the volume returns is under zero: -0.25, 0.5.

For example when the alarm vol is at the lowest:
![image](https://github.com/Pana-g/real_volume/assets/63166757/8fe2175d-d1b1-487a-a0f5-d4796beed5c0)

There is an `if` inside the listener when the volume is under zero. The current work around is just to remove this `if` and then I will receive the listen stream, but it should be fixed!

`VolumeChangeBroadcastReceiver`:
```dart
 @Override
    public void onReceive(Context context, Intent intent) {
        if (VOLUME_CHANGED_ACTION.equals(intent.getAction())) {
            CustomAudioService customAudioService = customAudioServiceWeakReference.get();
            if (customAudioService != null) {
                int streamType = intent.getIntExtra(EXTRA_VOLUME_STREAM_TYPE, -1);
                if(streamType >= 0 && streamType < 6) {
                    double volume = customAudioService.getCurrentVol(streamType);
                    //if (volume >= 0) {
                        customAudioService.onVolumeChanged(streamType, volume);
                    //}
                }
            }
        }

    }
```

Overall great package!

**Comment by dtkdt100** [comment]
![image](https://github.com/Pana-g/real_volume/assets/63166757/6751d0ee-b360-41a2-a2c4-a79fb0006112)

**Comment by Pana-g** [comment]
@dtkdt100 Package has been updated! Thanks for the feedback! #8

**Comment by dtkdt100** [comment]
Great, thanks!
