### ISSUE TITLE
Hide Android System Volume Toast/UI

### ISSUE THREAD

**Issue by mukhammad-akilov** [Pana-g/real_volume#9]
Is it possible to hide Android System Volume Toast/UI (for exmaple it appears when you press volume buttons). I want to attach event for volume buttons and not show this default UI

Example of Volume Toast:
![android_12_beta_2_volume_1](https://github.com/Pana-g/real_volume/assets/31181880/451b9f54-12f4-4195-a035-283cda6d8049)

!UPDATE
For example I have a page where I want to listen volum buttons click, but for example if users click volum up then I want to run some code without showing Volume UI and also not changing volume. So I want to disable default behavior of volume buttons.

Do you have any idea how I can do it with your plugin? @Pana-g

**Comment by Pana-g** [comment]
@mukhammad-akilov Unfortunately this package doesn't offer this kind of functionality.
